name: MKDG
description: MKDG
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.7+2
  google_fonts: ^0.2.0
  wakelock: ^0.1.3+3
  flutter_launcher_icons: ^0.7.2+1
  image: ^2.1.10
  cupertino_icons: ^0.1.2
  extended_math: ^0.0.29+1
  image_gallery_saver: ^1.2.2


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/mkdg.png"


flutter:
  uses-material-design: true
